media:
  input: assets/images
  output: assets/images
content:
  - name: snaps
    label: Snaps
    type: collection
    path: 'snaps'
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: cover
        label: Preview image
        type: image
      - name: cover_alt
        label: Cover Alt Text
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: tags
        label: Tags
        type: string
        list:
          min: 1 # Must have at least one tag
          max: 5 # Can have up to five tags
          default: [news]
  - name: training-log
    label: Activities
    type: collection
    path: 'training-log'
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: cover
        label: Preview image
        type: image
      - name: cover_alt
        label: Cover Alt Text
        type: string
      - name: description
        label: Description
        type: string
      - name: type
        label: Type
        type: select
        options:
          values: [ run, ride, climb, swim ]
      - name: time
        label: Time
        type: string
      - name: distance
        label: Distance
        type: number
      - name: pace
        label: Pace
        type: string
      - name: climg
        label: Climb
        type: number
      - name: hr
        label: HR
        type: number
      - name: w
        label: w
        type: number
      - name: kcal
        label: kcal
        type: number
      - name: tags
        label: Tags
        type: string
        list:
          min: 1 # Must have at least one tag
          max: 5 # Can have up to five tags
          default: [training-log]
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: Site settings
    path: /data/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)