media:
  - name: images # Note: 'name' key is required here
    label: Images
    input: assets/images
    output: assets/images
    extensions: webp
content:
  - name: snaps
    label: Snaps
    path: snaps
    type: collection
    fields: [ title, date, cover, cover_alt, description, "tags[0]" ]
